### ISSUE TITLE
Do you know what `NaN` means in spanish

### ISSUE THREAD

**Issue by german-rodriguez** [ucu-compil/quaero-lang#2]
Hey! I don't intend to be a troll here, just informative.
Maybe you already know, but in the "Rio de la Plata" at least (basically, Uruguay and Argentina), NaN is a value that evaluates to false as a boolean. I'm pretty sure that all the other spanish speaking countries will understand the same for that value.
That's actually quite funny (specially because is "really small" haha), but also something you should consider in case you want to make your lib mainstream.
Bests!

**Comment by juanlaube** [comment]
Array(16).join("lol" - 2) + " Batman!";
